### ISSUE TITLE
Version differences between npm and GitHub?

### ISSUE THREAD

**Issue by chriswiggins** [TallerWebSolutions/apollo-cache-instorage#2]
Hi there,

Really interesting package you have here and I'm really keen to start using it! I'm having an issue with the `__persist` field getting passed on to the HTTPLink, but I'm unable to debug it as the npm version is **0.2.4** whereas only **0.2.2** is here on Github?

Happy to contribute to the package - just need to get the latest sources 👍 

Cheers

**Comment by lucasconstantino** [comment]
@chriswiggins I can give you edit access to this repository if you wish. Help is very welcome, and I'm not currently using the package on any project of mine - though it is in the roadmap - so I'm not finding the time to conciliate my work with this.

**Comment by chriswiggins** [comment]
@lucasconstantino that'd be great! Can you do a push from your local branch too?

**Comment by lucasconstantino** [comment]
Just did ;)
