### ISSUE TITLE
React-Native Support

### ISSUE THREAD

**Issue by juddey** [TallerWebSolutions/apollo-cache-instorage#4]
Just wondering if this library is designed to be compatible with React Native. Saw lots of WebStorage mentioned, and since Async Storage has the same api as Webstorage afaik, it sounds like it _might_ work?

https://facebook.github.io/react-native/docs/asyncstorage.html

A simple yes or no answer would suffice, I don't want to chew up your time.

Thanks!

**Comment by lucasconstantino** [comment]
It might work.

Basically, when I refer to "WebStorage" I'm only referring to the _interface_; nothing related to the web browser, though.

**Comment by juddey** [comment]
Its worth a shot!  I shall give it a try and report back findings.

**Comment by juddey** [comment]
Unfortunately, didn't have any success with this. :disappointed: 
![image](https://user-images.githubusercontent.com/7445602/50258739-d7308500-0465-11e9-9956-14b35ff97f17.png)

**Comment by sampsonjoliver** [comment]
Wouldn't a simple enough wrapper on AsyncStorage (or filesystem storage) work here, though, if the problem is just to do with the WebStorage interface?

@juddey I know it's been a while but can you recall what steps you took for the above?

**Comment by juddey** [comment]
Sorry @sampsonjoliver - no idea!
