### ISSUE TITLE
Empty responses for any query

### ISSUE THREAD

**Issue by yantakus** [TallerWebSolutions/apollo-cache-instorage#6]
I'm trying to use this package as a drop in replacement for `apollo-cache-inmemory`. But in this case I get empty object for `data` in response for any query. Data gets from the server and is persisted (I see items in localStorage), but nothing comes from the queries. Any ides? How do I debug this at all?

**Comment by lucasconstantino** [comment]
Sorry dude, I'm short on time for debugging right now. Do you mind to setup a reproduction case? It can be on CodeSandbox, for instance.

**Comment by adrian1388** [comment]
Hello @lucasconstantino.
I see this project very valuable for my purposes and I have played with it a lil' but I have found this issue and I am blocked here right now.

I have made a test project for you to clone, install and link it `react-native link` (I could not get it working on Sandbox), then I am sure you can help us.

It is a simple use of the Query component where data comes as an empty object.

Also, I had to do two changes to your code to get the project working, please read the README file first.

https://github.com/adrian1388/ReactNativeInstorageTest

I am going to be waiting for your answer.

**Comment by adrian1388** [comment]
@lucasconstantino  Running your test file named 'inStorageCache.test.js' and adding a debug on objectStorageCache.js#get(), like this:
```js

  get (dataId) {
    if (!this.data[dataId] && this.persistence.shouldPersist('get', dataId)) {
      console.info(this.persistence.storage)
      this.data[dataId] = this.persistence.denormalize(
        this.persistence.storage.getItem(`${this.persistence.prefix}${dataId}`)
      )
    }
    return this.data[dataId]
  }
```


I can see the next output:

for some cases:
```sh
  console.info src/objectStorageCache.js:57
    LocalStorage {}
```

and in other cases LocalStorage contains a Query result:
```sh
  console.info src/objectStorageCache.js:57
    LocalStorage {
      '$ROOT_QUERY.typeField': '{"field":"value","__typename":"TypeName"}' }
```


Is not it supposed that brings an output like this:   ...?
```console
{setItem: ƒ, getItem: ƒ, removeItem: ƒ, getAllKeys: ƒ}
```

**Comment by adrian1388** [comment]
FYI:

- I have made a test with InMemoryCache and the query works OK.

**Comment by lukadriel7** [comment]
Hello, any news concerning this issue ?

**Comment by lucasconstantino** [comment]
@yantakus @adrian1388 @lukadriel7 can any of you have a look at #7 if it fixes your issue?

**Comment by lukadriel7** [comment]
@lucasconstantino hello, thanks for checking the issue. I don't know if the pull request fix the issue. I installed the package from npm so unless there is a merge and a version bump, I won't be able to tell.
Is there another way I can test it ? I will be happy to do so.

**Comment by lukadriel7** [comment]
@lucasconstantino it solves the problem thank you . I cloned the package and built it with the changes. it works.
That being said, are you planning on keeping on maintaining this package ? You seem really busy

**Comment by lucasconstantino** [comment]
Hey, @lukadriel7. Thanks for validating the solution. I've already closed the PR and pushed a new version on NPM.

I usually only keep maintenance on projects I'm currently using, and if I face issues. Definitely, due to scarce time. I'm always looking forward to receive support on the projects, though, and quite often I simply give ownership to someone more currently involved on it.
